'''
Make soft-links for data generated by 
Upenn NGSC to the target snakemake project
folder.

Zijun Zhang
June 11, 2018
'''

import os
import sys
import re

if len(sys.argv) != 4:
	print("usage: python program.py <barcode.txt> <source_dir> <target_dir>")
	sys.exit(1)

barcode_fn = sys.argv[1]
source_dir = os.path.realpath(sys.argv[2])
target_dir = os.path.realpath(sys.argv[3])

barcode_to_sample = {}
## Barcode File format: BARCODE SAMPLE_NAME
with open(barcode_fn, 'r') as f:
	for line in f:
		if line.startswith('#'):
			continue
		ele = line.strip().split()
		barcode_to_sample[ele[0]] = ele[1]

print(barcode_to_sample)
source_fn_list = [x for x in os.listdir(source_dir) if x.endswith('.gz')]

for fn in source_fn_list:
	this_barcode = fn.split('.')[0].split('_')[4]
	paired_end = fn.split('.')[0].split('_')[3]
	if this_barcode in barcode_to_sample:
		sample = barcode_to_sample[this_barcode]
		sample_dir = os.path.join(target_dir, sample)
		if not os.path.isdir(sample_dir):
			os.mkdir(sample_dir)
		cmd = "ln -sf %s %s"%( 
			os.path.join(source_dir, fn),
			os.path.join(sample_dir, this_barcode+"_"+paired_end+'.fastq.gz')
			)
		print(cmd)
		os.system(cmd)